spring:
  application:
    name: GRPC-SERVER

  #################
  ## Auto Configure
  #################

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #################
  ## Servlet
  #################

  servlet:
    multipart:
      enabled: true

###################
## Web Container
###################

server:
  port: 8080
  address: 0.0.0.0

#################
## Application
#################

app:

#################
## Logging
#################

logging:
  config: src/main/resources/logback.xml
